### ISSUE TITLE
GUI won't start

### ISSUE THREAD

**Issue by sojusnik** [Xunius/Menotexport#2]
When launching the GUI in the shell the following appears:

```
xxx@yyy:~$ /home/sojusnik/Test/menotexport-gui.py
Traceback (most recent call last):
  File "/home/sojusnik/Test/menotexport-gui.py", line 29, in <module>
    import menotexport
  File "/home/sojusnik/Test/menotexport.py", line 30, in <module>
    from lib import extracthl
  File "/home/sojusnik/Test/lib/extracthl.py", line 17, in <module>
    from pdfminer.pdfdocument import PDFDocument
ImportError: No module named pdfdocument
```

Happens on Ubuntu 15.10 with apparently all required packages installed.

**Comment by Xunius** [comment]
Thanks for reporting.
Seems it stopped at the pdfdocument module. 
Can you verity the version of pdfminer and python? pdfminer doesn't support python3, and from the changelog of pdfminer it seems that the author made some structural changes in the 2013-Nov update. So please try install the 2014+ version and let me if it works.

**Comment by sojusnik** [comment]
Yes, my pdfminer version (installed from the official Ubuntu repository) wasn't up to date. After manually installing the new one, everything started to work. Thanks!
