### ISSUE TITLE
Troubles with multi-document entries

### ISSUE THREAD

**Issue by matteosecli** [Xunius/Menotexport#26]
It's quite common for papers to have "Supplementary Materials", most of the times additional PDF files with extra info. I usually save these extra materials as additional PDF files in the paper entry; however, it seems that Menotexport discards them during the export process. I have an entry with the following 2 PDF files:

- the article itself, say `article.pdf`
- the supplementary materials, say `supplementary.pdf`

For some weird reason, Mendeley has decided that `supplementary.pdf` is the "primary" PDF file of the entry, i.e. the file that gets opened when you double-click on the paper entry on Mendeley. If I want to open the main text, I have to click on the second file on the file list of the entry, in Mendeley's right panel. Annoying, but not a big deal.

However, if I export the document with Menotexport, only the "primary" file (which in this case Mendeley has decided to be `supplementary.pdf`) gets exported. What's even more strange is that both files have their own notes; however, `supplementary.pdf` gets exported with the highlights belonging to `article.pdf` baked in it, which obviously looks like a complete non-sense when I open it.

By digging around, I've found that [this](https://github.com/cycomanic/Menextract2pdf) Python program, instead, does the export in the correct way (i.e., it exports both PDF files and each of them with its own highlights).

I can provide screenshots of the entry in Mendeley and/or the relevant PDF files, if you need them.

**Comment by Xunius** [comment]
Hi matteosecli,

Yes that's a legit complaint, something I overlooked when making this tool. No need for screenshots or pdfs, the issue appears quite clear, but it might take some time for me to fix it. In the meanwhile, you could create a separate entry for the supplementary in Mendeley, or use some other tools if they do it properly.

Sorry for the trouble.

**Comment by matteosecli** [comment]
No worries, thank you! 😄

**Comment by matteosecli** [comment]
Closing as fixed in https://github.com/Xunius/Menotexport/commit/a5b383994aaee66e04bdffccd70e9050fd6c6875, https://github.com/Xunius/Menotexport/commit/f8560c4c75761b51b42a7bff42b082c15b43f3b5 and https://github.com/Xunius/Menotexport/commit/e9abd4ff0fc68a35ee0188bb0623a48911637c5a.
