### ISSUE TITLE
Doesn't Work on Windows 10

### ISSUE THREAD

**Issue by monitizer** [Xunius/Menotexport#7]
Hi Jason,
Thank you so much for creating the windows tool, it looks awesome. Unfortunately, it is not working for me as it does anything after this message:

Start processing...
# 
# <menotexport>: Connected to database:

C:/Users/Research/AppData/Local/Mendeley Ltd/Mendeley
Desktop/mendeley@mydomain.com@www.mendeley.com.sqlite

Could you please let me know how i could make it work?

**Comment by Xunius** [comment]
Hi,
Please provide me with some more info regarding your usage:
What's your Mendeley version?
Did you set up a python environment on win 10 and run the code, or did you download a build version of Menotexport for win10 from dropbox or onedrive? Note that if you run your own python and run the code, it won't work for python 3, only for python 2.
And finally what actions are you performing, export PDFs or something else?

Thanks

**Comment by monitizer** [comment]
Hi Jason,

Thank you for getting back to me.

No python environment set on Win 10. I am using the pre-build version Windows 10  (1.4) (https://dl.dropboxusercontent.com/u/74222489/Menotexport-win10-64.rar)

I have the latest version of Mendeley: 1.17

Steps:
1. I set the path of my Mendeley data file and out put folder.
2. I select export pdfs, extract highlights, extract notes, save seperately
3. Click Start

After that nothing happens other than the Start processing. (see attachment)
http://content.screencast.com/users/bestoffer/folders/Jing/media/e52f1054-5ab0-4b8a-a7a6-5fe469a2a460/2016-10-13_0246.png

Look forward to hearing from you.

Thanks

**Comment by Xunius** [comment]
Hi,
Thanks for all the info. 
I'll look into it deeper, but at first glance the "Mendeley folder" dropdown menu is empty from your screenshot. If I remember correctly when selecting a folder, or select to process all folders, it will print a line of message in the message box.
So could you please give it one more try by clicking into that menu and select something and see if it works?
Thanks

**Comment by monitizer** [comment]
Hi,
Thank you for getting back to me.
I did selected all folders but when i start it is de-selected. Secondly i noticed i can't see any other option in this dropdown except to select all folders.
Thanks

**Comment by Xunius** [comment]
Hi,
Then there's indeed something gone wrong. Could you let me know do you have any folders in your mendeley library?
I'll do some more tests in this weekend and hopefully get it fixed by next Monday. Sorry for the trouble.

**Comment by Xunius** [comment]
Hi,
This is technically not a fix but a quick workaround: it turns out that if you have no folders in the Mendeley library, but save all documents under "My Library", that problem occurs.
So, if you need to get your job done quickly, I suggest creating a folder, and copy all docs into that, then in Menotexport select that folder to process. In the mean while I will look into this for a real solution. Hope that helps.

**Comment by Xunius** [comment]
Hi monitizer,
How is it going, does the workaround work? I've made an update that hopefully would solve the problem, please check out the new dropbox download.

**Comment by monitizer** [comment]
Hi Jason,
It's amazing. I can't thank you enough for the fix. I was able to extract my notes and highlights great tool man. God bless you for this (Y)
PS: Sorry to reply you late.
Thanks

**Comment by Xunius** [comment]
Hi monitizer,
Glad that it works for you. Good luck with your work.
